{
TCanvas* Clov1 = new TCanvas();
h0_Clov->Draw();
h1_Clov->SetLineColor(2);
h1_Clov->Draw("same");
h2_Clov->SetLineColor(3);
h2_Clov->Draw("same");
h3_Clov->SetLineColor(5);
h3_Clov->Draw("same");
TCanvas* Clov2 = new TCanvas();
h4_Clov->Draw();
h5_Clov->SetLineColor(2);
h5_Clov->Draw("same");
h6_Clov->SetLineColor(3);
h6_Clov->Draw("same");
h7_Clov->SetLineColor(5);
h7_Clov->Draw("same");
TCanvas* Clov3 = new TCanvas();
h8_Clov->Draw();
h9_Clov->SetLineColor(2);
h9_Clov->Draw("same");
h10_Clov->SetLineColor(3);
h10_Clov->Draw("same");
h11_Clov->SetLineColor(5);
h11_Clov->Draw("same");
TCanvas* Clov4 = new TCanvas();
h12_Clov->Draw();
h13_Clov->SetLineColor(2);
h13_Clov->Draw("same");
h14_Clov->SetLineColor(3);
h14_Clov->Draw("same");
h15_Clov->SetLineColor(5);
h15_Clov->Draw("same");
TCanvas* Clov5 = new TCanvas();
h16_Clov->Draw();
h17_Clov->SetLineColor(2);
h17_Clov->Draw("same");
h18_Clov->SetLineColor(3);
h18_Clov->Draw("same");
h19_Clov->SetLineColor(5);
h19_Clov->Draw("same");
TCanvas* Clov6 = new TCanvas();
h20_Clov->Draw();
h21_Clov->SetLineColor(2);
h21_Clov->Draw("same");
h22_Clov->SetLineColor(3);
h22_Clov->Draw("same");
h23_Clov->SetLineColor(5);
h23_Clov->Draw("same");

}
